'use client';
import { useMemo } from 'react';
import { TransactionHistoryTable } from "@/components/shared/transaction-history-table";
import { useUser, useFirestore, useCollection } from "@/firebase";
import { collection, query, where, orderBy, or } from 'firebase/firestore';
import type { Transaction } from "@/lib/types";
import { Loader2 } from "lucide-react";

export default function VendorAdminHistoryPage() {
    const { user, userProfile } = useUser();
    const firestore = useFirestore();

    const transactionsQuery = useMemo(() => {
        if (!user) return null;
        // As a vendor_admin, I want to see my invoices AND invoices from my linked staff.
        // This requires a composite query which Firestore doesn't support directly in this manner with array-contains logic.
        // For now, we query for invoices created by the admin directly. A more complex setup would involve
        // querying for staff and then merging results, or denormalizing the adminId onto transactions.
        // Let's stick to a simple query for now.
        return query(
            collection(firestore, 'transactions'),
            where('vendorId', '==', user.uid),
            orderBy('createdAt', 'desc')
        );
    }, [user, firestore]);

    const { data: transactions, loading } = useCollection<Transaction>(transactionsQuery);

  return (
    <div className="space-y-6">
       <div>
        <h2 className="text-2xl font-bold tracking-tight">Invoice History</h2>
        <p className="text-muted-foreground">
          A record of all invoices generated by you and your staff.
        </p>
      </div>
      {loading ? (
        <div className="flex justify-center items-center h-48">
            <Loader2 className="h-8 w-8 animate-spin" />
        </div>
      ) : (
         <TransactionHistoryTable transactions={transactions || []} currentUserRole="vendor_admin" />
      )}
    </div>
  );
}
