// This file is automatically generated by the Firebase setup.
// Do not edit this file manually.

// This configuration is meant for the client-side and is safe to expose.
// It does not contain any sensitive information.

// TODO: Replace with your actual Firebase project configuration.
export const firebaseConfig = {
  apiKey: "AIzaSyCth1KIL2qCawS-YpocjSwPUu-rMg2-qBY",
  authDomain: "canonic-erp.firebaseapp.com",
  projectId: "canonic-erp",
  storageBucket: "canonic-erp.appspot.com",
  messagingSenderId: "623454368743",
  appId: "1:623454368743:web:f04e649223d29737780342",
};
